default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  # -----------------------------  Security Tools ---------------------------- #

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
        name: " security 路 Detect hardcoded secrets"

  # ---------------------------  Code Quality Tools -------------------------- #

  ### GoLang ###
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: golangci-lint-repo-mod
        name: " Go 路 Lint with golangci-lint"
        args: ['-c', './ci/config/.golangci.yml', '--fix']
      - id: go-test-repo-mod
        name: "И Go 路 Run unit tests"
        args: [-tags=unit]
      - id: go-test-repo-mod
        name: "И Go 路 Run integration tests"
        args: [-tags=integration]
        stages: [pre-push]

  ### Makefile ###
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        name: " Makefile 路 Lint Makefile"

  # ------------------------------ 锔 General Tools ------------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # ----------------------------  Filesystem Tools --------------------------- #
      - id: check-yaml
        name: " filesystem/ check 路 Check yaml"
      - id: check-json
        name: " filesystem/ check 路 Check json"
        exclude: ^\.vscode/.*\.json$
      - id: pretty-format-json
        name: " filesystem/ format 路 Format json"
        exclude: ^\.vscode/.*\.json$
        args: ['--autofix']
      - id: end-of-file-fixer
        name: " filesystem/ format 路 Fix EOL"
      - id: trailing-whitespace
        name: " filesystem/ format 路 Trailing whitespaces"
      - id: check-executables-have-shebangs
        name: " filesystem/锔 exec 路 Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: " filesystem/锔 exec 路 Verify script permissions"
      - id: check-case-conflict
        name: " filesystem/ names 路 Check case sensitivity"
      - id: check-illegal-windows-names
        name: " filesystem/ names 路 Validate Windows filenames"
      - id: check-symlinks
        name: " filesystem/ symlink 路 Check symlink validity"
      # -------------------------------  Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: " git 路 Detect conflict markers"
      # - id: forbid-new-submodules
      #   name: " git 路 Prevent submodule creation"
      # - id: no-commit-to-branch
      #   name: " git 路 Protect main branches"
      #   args: ["--branch", "main", "--branch", "master"]
      - id: check-added-large-files
        name: " git 路 Block large file commits"
        args: ['--maxkb=5000']
